some changes

diff --git a/contrib/android/make_apk b/contrib/android/make_apk
--- a/contrib/android/make_apk
+++ b/contrib/android/make_apk
@@ -10,9 +10,9 @@ LOCALE="$PROJECT_ROOT"/electrum/locale/
 
 . "$CONTRIB"/build_tools_util.sh
 
-if [ ! -d "$PACKAGES" ]; then
-  "$CONTRIB"/make_packages || fail "make_packages failed"
-fi
+#if [ ! -d "$PACKAGES" ]; then
+ # "$CONTRIB"/make_packages || fail "make_packages failed"
+#fi
 
 pushd "$PROJECT_ROOT"
 git submodule update --init
@@ -46,20 +46,15 @@ if [[ -n "$1"  && "$1" == "release" ]] ; then
     export P4A_RELEASE_KEYALIAS_PASSWD=$password
     export P4A_RELEASE_KEYALIAS=electrum
     # build two apks
-   # export APP_ANDROID_ARCH=armeabi-v7a
-   # make release
-	#emulator 29+
+    export APP_ANDROID_ARCH=armeabi-v7a
+    make release
     export APP_ANDROID_ARCH=arm64-v8a
     make release
 elif [[ -n "$1"  && "$1" == "release-unsigned" ]] ; then
     # do release build, but do not sign the APKs.
     # build two apks
-#    export APP_ANDROID_ARCH=armeabi-v7a
-#    make release
- #   export APP_ANDROID_ARCH=arm64-v8a
-  #  make release
-    
-    #emulator 29+
+    export APP_ANDROID_ARCH=armeabi-v7a
+    make release
     export APP_ANDROID_ARCH=arm64-v8a
     make release
 else
@@ -77,11 +72,7 @@ else
             -keypass "$P4A_DEBUG_KEYALIAS_PASSWD"
     fi
     # only build one apk for debug build, for faster testing iterations
-   # export APP_ANDROID_ARCH=arm64-v8a
-  #  make apk
-    export APP_ANDROID_ARCH=x86_64
-    make apk
-    export APP_ANDROID_ARCH=x86
+    export APP_ANDROID_ARCH=arm64-v8a
     make apk
     # export APP_ANDROID_ARCH=armeabi-v7a
     # make apk
