changes for android binary built

diff --git a/contrib/android/make_apk b/contrib/android/make_apk
--- a/contrib/android/make_apk
+++ b/contrib/android/make_apk
@@ -10,9 +10,9 @@ LOCALE="$PROJECT_ROOT"/electrum/locale/
 
 . "$CONTRIB"/build_tools_util.sh
 
-#if [ ! -d "$PACKAGES" ]; then
- # "$CONTRIB"/make_packages || fail "make_packages failed"
-#fi
+if [ ! -d "$PACKAGES" ]; then
+  "$CONTRIB"/make_packages || fail "make_packages failed"
+fi
 
 pushd "$PROJECT_ROOT"
 git submodule update --init
